Repository ivandi1980/my-go, pull requests merged in 2023-03, with the labels that each got.

#1 ObserverPattern added
  go.mod
  main.go
  pattern/ObserverPattern.go
Labels: enhancement

#2 ObserverPattern code updated!
  main.go
  pattern/ObserverPattern.go
Labels: bug, enhancement

#3 PrototypePattern added!
  README.md
  main.go
  pattern/ObserverPattern.go
  pattern/PrototypePattern.go
Labels: bug, documentation, enhancement

#4 SingletonPattern added!
  main.go
  pattern/SingletonPattern.go
Labels: bug, documentation, enhancement

#6 Readme Updated!!
  README.md
Labels: documentation, enhancement
